language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7

script:
  # Compile and run unit tests
  - mvn test -B
  # Validate code style
  - mvn validate -B

# In addition to pull requests, always build these branches
branches:
  only:
    - master
